### ISSUE TITLE
Navigation between notebooks on remote

### ISSUE THREAD

**Issue by lmoresi** [ANU-RSES-Education/EMSC-4033#14]
We launch into jupyter (classic) because it keeps things neat but it can be hard to find where to go next.

**Comment by navidcy** [comment]
Are you referring to the `Launch Demo` button?

**Comment by lmoresi** [comment]
It's a jupyterbook think - when you launch a page it first goes through nbgitpuller and then lands in a notebook. To navigate back to the main book, the first back link is to the nbgitpuller page again. It's ugly but I think it's just the way things are for the time being.
