### ISSUE TITLE
Exercise 14 - Pandas - Already completed 

### ISSUE THREAD

**Issue by fayewill** [ANU-RSES-Education/EMSC-4033#29]
Hi Louis and Navid, 

It appears as though Exercise 14 - Pandas has already been completed- all the outputs are there. 

Are you able to reset?

Thanks

Faye

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1619762468/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/c4904163a4b36ae09bb8e1d09dca12ad/9efab2399c7c560b34de477b9aa0a465/newton.gif]
I would suggest “clear all cells” in the notebook I don’t want to risk creating git conflicts until we are all together to fix things.

Prof Louis Moresi
***@***.******@***.***>
(m) +61 4 0333 1413<tel:+61403331413>
(us) +1 505 349 4425<tel:+15053494425>
www.moresi.info<https://tr.cloudmagic.com/h/v6/link-track/1.0/1619762486261732-908c3b89-92e3-c3c9-ddb3-8637a3fe07ad/1619762468/e0463a85314d353cd65b915287a67da9/c4904163a4b36ae09bb8e1d09dca12ad/9efab2399c7c560b34de477b9aa0a465?redirect_uri=http://www.moresi.info/>
geo-down-under.geoscience.education<https://tr.cloudmagic.com/h/v6/link-track/1.0/1619762486261744-a3776fd9-e3b7-bace-d1a7-aeaddfd5ac79/1619762468/e0463a85314d353cd65b915287a67da9/c4904163a4b36ae09bb8e1d09dca12ad/9efab2399c7c560b34de477b9aa0a465?redirect_uri=https://geo-down-under.geoscience.education/>
@LouisMoresi<https://tr.cloudmagic.com/h/v6/link-track/1.0/1619762486261750-2a0ca344-5d5c-7fa5-a965-1676f1c86f1e/1619762468/e0463a85314d353cd65b915287a67da9/c4904163a4b36ae09bb8e1d09dca12ad/9efab2399c7c560b34de477b9aa0a465?redirect_uri=https://twitter.com/LouisMoresi>

On Fri, Apr 30, 2021 at 15:59, Faye Williamson ***@***.******@***.***>> wrote:

Hi Louis and Navid,

It appears as though Exercise 14 - Pandas has already been completed- all the outputs are there.

Are you able to reset?

Thanks

Faye
