### ISSUE TITLE
Exercise 14 (Pandas) requires `xlrd` package

### ISSUE THREAD

**Issue by navidcy** [ANU-RSES-Education/EMSC-4033#30]
```python
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
```

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1620259289/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/b1fa4275a05f0d4503ded5d23ad36713/9efab2399c7c560b34de477b9aa0a465/newton.gif]
And I actually had to install `openpyxl`.

We should add these to the `conda environment yaml file`

Prof Louis Moresi
***@***.***
(m) +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
geo-down-under.geoscience.education<https://geo-down-under.geoscience.education/>
@LouisMoresi<https://twitter.com/LouisMoresi>

On Thu, May 6, 2021 at 9:06 AM, Navid C. Constantinou ***@***.***> wrote:

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

**Comment by lmoresi** [comment]
I've updated that and it will probably propagate through to the hub without causing any trouble.
