### ISSUE TITLE
Bug in `Notebooks/Themes/Mapping/8-GlobalPlateMotionsEtc.md `

### ISSUE THREAD

**Issue by navidcy** [ANU-RSES-Education/EMSC-4033#31]
@fzhang0 claimed that there is a but here:
`EMSC-4033/Notebooks/Themes/Mapping/8-GlobalPlateMotionsEtc.md`

@fzhang0, could you elaborate a bit on this and mention what you did to fix it?

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1621222793/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/f50f692934889e08526dc695f231ed9c/9efab2399c7c560b34de477b9aa0a465/newton.gif]
Is it the typo in cell 3 ?

teaching_data.download_file_if_distinct("etopo1_grayscale_hillshade.tif", "Resources/etopo1_grayscale_hillshade.tif")ETOPO1_Ice_c_geotiff.tif

Should be

teaching_data.download_file_if_distinct("etopo1_grayscale_hillshade.tif", "Resources/etopo1_grayscale_hillshade.tif”)

Not sure how that happened.


Prof Louis Moresi
***@***.***
(m) +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
www.geo-down-under.org.au<https://www.geo-down-under.org.au/>
@LouisMoresi<https://twitter.com/LouisMoresi>

On Mon, May 17, 2021 at 10:44 AM, Navid C. Constantinou ***@***.***> wrote:

@fzhang0<https://github.com/fzhang0> claimed that there is a but here:
EMSC-4033/Notebooks/Themes/Mapping/8-GlobalPlateMotionsEtc.md

@fzhang0<https://github.com/fzhang0>, could you elaborate a bit on this and mention what you did to fix it?
