### ISSUE TITLE
deploy-book fails

### ISSUE THREAD

**Issue by navidcy** [ANU-RSES-Education/EMSC-4033#33]
https://github.com/ANU-RSES-Education/EMSC-4033/runs/2868696182?check_suite_focus=true

@lmoresi any ideas?

**Comment by lmoresi** [comment]
Yep - version creep on jupyter book and a breaking change.

Prof Louis Moresi
***@***.******@***.***>
(m) +61 4 0333 1413<tel:+61403331413>
(us) +1 505 349 4425<tel:+15053494425>
www.moresi.info<https://tr.cloudmagic.com/h/v6/link-track/1.0/1624190466792980-e37544df-7089-734a-d821-d2325103f3ce/1624190449/e0463a85314d353cd65b915287a67da9/f538e0066646e4fa6a0d08ef55f6f24d/9efab2399c7c560b34de477b9aa0a465?redirect_uri=http://www.moresi.info/>
www.geo-down-under.org.au<https://tr.cloudmagic.com/h/v6/link-track/1.0/1624190466792999-fbdd5e46-fb7b-f2ad-0b65-fdbe59ec3ad8/1624190449/e0463a85314d353cd65b915287a67da9/f538e0066646e4fa6a0d08ef55f6f24d/9efab2399c7c560b34de477b9aa0a465?redirect_uri=https://www.geo-down-under.org.au/>
@LouisMoresi<https://tr.cloudmagic.com/h/v6/link-track/1.0/1624190466793007-c6a5af03-631d-6178-db88-17c8dfd4b237/1624190449/e0463a85314d353cd65b915287a67da9/f538e0066646e4fa6a0d08ef55f6f24d/9efab2399c7c560b34de477b9aa0a465?redirect_uri=https://twitter.com/LouisMoresi>

On Sun, Jun 20, 2021 at 21:36, Navid C. Constantinou ***@***.******@***.***>> wrote:

https://github.com/ANU-RSES-Education/EMSC-4033/runs/2868696182?check_suite_focus=true<https://tr.cloudmagic.com/h/v6/link-track/1.0/1624190466793015-7730f830-12f4-3518-bd91-6e0dd6eee769/1624190449/e0463a85314d353cd65b915287a67da9/f538e0066646e4fa6a0d08ef55f6f24d/9efab2399c7c560b34de477b9aa0a465?redirect_uri=https://github.com/ANU-RSES-Education/EMSC-4033/runs/2868696182?check_suite_focus=true>

@lmoresi<https://github.com/lmoresi> any ideas?

**Comment by lmoresi** [comment]
Resolved in commit 22157181a87edaf43f6d36ea24723b1598451ba9
