### ISSUE TITLE
Madhava of Sangamagrama needs an !

### ISSUE THREAD

**Issue by g-nym** [ANU-RSES-Education/EMSC-4033#35]
The Madhava of Sangamagrama equation requires a factorial on the denominator

**Comment by navidcy** [comment]
Can you point where exactly in the notes this is?

**Comment by navidcy** [comment]
Or feel free to open a PR.

**Comment by navidcy** [comment]
Hm, I think it doesn't need any factorial. Have a look at https://en.wikipedia.org/wiki/Approximations_of_π

**Comment by lmoresi** [comment]
I think we can close this
